######### POSTGRESQL #########
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/regions
spring.r2dbc.username=postgres
spring.r2dbc.password=postgres

######### Flyway #########
spring.flyway.url=jdbc:postgresql://localhost:5432/regions
spring.flyway.user=postgres
spring.flyway.password=postgres
spring.flyway.locations=classpath:db/migration