spring.application.name=region-data-service
spring.profiles.active=${ACTIVE_PROFILE:local}

######### BDL #########
bdl.api.url=https://bdl.stat.gov.pl/api/v1
bdl.api.key=${BDL_API_KEY}

######### Metrics #########
management.endpoints.web.exposure.include=health,info,prometheus
management.otlp.metrics.export.enabled=true
management.otlp.metrics.export.url=https://otlp-gateway-prod-eu-west-2.grafana.net/otlp/v1/metrics
management.otlp.metrics.export.headers.authorization=${OTEL_API_KEY}
management.otlp.metrics.export.step=60s
management.opentelemetry.resource-attributes.deployment.environment=${ACTIVE_PROFILE:local}
