spring.application.name=region-analytics-service

######### BDL #########
bdl.api.url=https://bdl.stat.gov.pl/api/v1
bdl.api.key: ${BDL_API_KEY}

######### POSTGRESQL #########
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/regions
spring.r2dbc.username=postgres
spring.r2dbc.password=postgres

spring.flyway.url=jdbc:postgresql://localhost:5432/regions
spring.flyway.locations=classpath:db/migration

######### Metrics #########
management.endpoints.web.exposure.include=health,info,prometheus