spring.application.name=region-analytics-service
spring.profiles.active=local

######### BDL #########
bdl.api.url=https://bdl.stat.gov.pl/api/v1
bdl.api.key=${BDL_API_KEY}

######### Metrics #########
management.endpoints.web.exposure.include=health,info,prometheus